resolver: lts-3.16
packages:
  - location:
      git: https://github.com/eryx67/api-builder.git
      commit: 4c4c75054d0f0978dcd2d594f2dae4470466e680
  - location:
      git: https://github.com/eryx67/vk-api.git
      commit: 73665a2a3a3ac3b9115fd12360c3bc7191dcb0f8
  - '.'
extra-deps:
  - aeson-0.9.0.1
  - aeson-casing-0.1.0.2
  - data-default-generics-0.3
  - fraction-0.1.0.4
  - react-flux-1.0.2
  - suspend-0.2.0.0
  - timers-0.2.0.3
  - uri-0.1.6.3
  - web-routes-0.27.9
  - web-routes-th-0.22.3
  - attoparsec-0.13.0.1
